{% set name = "tensor-sensor" %}
{% set version = "1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tensor-sensor-{{ version }}.tar.gz
  sha256: 5406c746ac3706a75f1a18b3f7e44125c39970d3cde5480f78bef16eacf2c93b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python-graphviz >=0.14.1
    - ipython
    - matplotlib-base
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - tsensor.analysis
    - tsensor.ast
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/parrt/tensor-sensor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The goal of this library is to generate more helpful exception messages for matrix algebra expressions for numpy, pytorch, jax, tensorflow, keras, fastai.
  description: |
    TensorSensor clarifies exceptions by augmenting messages and 
    visualizing Python code to indicate the shape of tensor variables.
  doc_url: https://github.com/parrt/tensor-sensor
  dev_url: https://github.com/parrt/tensor-sensor

extra:
  recipe-maintainers:
    - jan-janssen
